name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('yarn.lock') }}

    - name: Instal dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: Cache node modules @ example
      uses: actions/cache@v1
      id: cache-example
      with:
        path: ./example/node_modules
        key: node-modules-example--${{ hashFiles('example/yarn.lock') }}

    - name: Instal dependencies @ example
      if: steps.cache-example.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --cwd ./example


  test:
    needs: build
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('yarn.lock') }}

    - name: Cache node modules @ example
      uses: actions/cache@v1
      id: cache-example
      with:
        path: ./example/node_modules
        key: node-modules-example--${{ hashFiles('example/yarn.lock') }}

    - name: Run tests
      run: |
        yarn run lint
        yarn run tsc
        yarn run test
